services:
  db:
    image: postgres:latest
    container_name: DB_POSTGRES
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build: ./api
    container_name: BACK_DJANGO
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: ./front
    container_name: FRONT_VUE
    ports:
      - "5173:5173"
    depends_on:
      - back

  backup:
    build: ./backup
    container_name: BACKUP_SERVICE
    restart: on-failure
    volumes:
      - backup_data:/backup
      - borg_repo:/borg-repo
    depends_on:
      - db

volumes:
  postgres_data:
  backup_data:
  borg_repo:
